Pandas

In [1]:
import pandas as pd
s=pd.Series([0.1, 1.2, 2.3, 3.4 ,9])

In [2]:
import numpy as np
a=np.array([0.1, 1.2, 2.3, 3.4, 9])
print(a)

[0.1 1.2 2.3 3.4 9. ]

In [3]:
#initialize a numpy array as a pandas series
s=pd.Series(a)

In [4]:
#Series indexes don't have to be integers
s = pd.Series(a, index=['a', 'b', 'c', 'd', 'e'])
s

a    0.1
b    1.2
c    2.3
d    3.4
e    9.0
dtype: float64

In [5]:
#Select element at 0 location
s.iloc[0]

np.float64(0.1)

In [6]:
#Select element with index a
s.loc['a']

np.float64(0.1)

In [7]:
#Select all elements from 2 to 4
s.iloc[2:4]

c    2.3
d    3.4
dtype: float64

In [8]:
#Unlike numpy, indexes need not be unique
s=pd.Series([0.1, 1.2, 2.3, 3.4, 9], index = ['a', 'b', 'c', 'a', 'a'])
s['a']

a    0.1
a    3.4
a    9.0
dtype: float64

In [9]:
#Often build panda series with dictionaries
s1 = pd.Series({'a': 0.1, 'b': 1.2, 'c': 2.3})

Can add and subtract series, and all values of the same index in both series will be operated on (a's with a's in both series, for example.)

In [10]:
s1.array

<NumpyExtensionArray>
[0.1, 1.2, 2.3]
Length: 3, dtype: float64

In [11]:
s.array

<NumpyExtensionArray>
[0.1, 1.2, 2.3, 3.4, 9.0]
Length: 5, dtype: float64

In [12]:
s.index

Index(['a', 'b', 'c', 'a', 'a'], dtype='str')

In [13]:
#First 5, or n, elements
s1.head()

a    0.1
b    1.2
c    2.3
dtype: float64

In [14]:
s1.head(1)

a    0.1
dtype: float64

In [15]:
#Bottom 5, or n, elements
s.tail()

a    0.1
b    1.2
c    2.3
a    3.4
a    9.0
dtype: float64

In [16]:
s.tail(3)

c    2.3
a    3.4
a    9.0
dtype: float64

In [17]:
#Summary stats
s.describe()

count    5.000000
mean     3.200000
std      3.467708
min      0.100000
25%      1.200000
50%      2.300000
75%      3.400000
max      9.000000
dtype: float64

In [18]:
s.isnull()

a    False
b    False
c    False
a    False
a    False
dtype: bool

Series are the building blocks of pandas, but the workhorse is the DataFrame, which collects multiple series in the same way spreadsheets collect multiple columns of data (series = column, index = row). Each series can have its own data type, unlike homogenous NumPy arrays.

In [23]:
#df = pd.Series([[1,6], [4,5]], columns = ["one", "two"])

In [21]:
state_gdp = pd.read_excel('US_state_GDP.xls', 'Sheet1')

In [22]:
state_gdp.head()

,state_code,state,gdp_2009,gdp_2010,gdp_2011,gdp_2012,gdp_growth_2009,gdp_growth_2010,gdp_growth_2011,gdp_growth_2012,region
0,AK,Alaska,44215,43472,44232,44732,7.7,-1.7,1.7,1.1,FW
1,AL,Alabama,149843,153839,155390,157272,-3.9,2.7,1.0,1.2,SE
2,AR,Arkansas,89776,92075,92684,93892,-2.0,2.6,0.7,1.3,SE
3,AZ,Arizona,221405,221016,224787,230641,-8.2,-0.2,1.7,2.6,SW
4,CA,California,1667152,1672473,1692301,1751002,-5.1,0.3,1.2,3.5,FW

In [24]:
#Select by column
state_gdp['gdp_2009'].head()

0      44215
1     149843
2      89776
3     221405
4    1667152
Name: gdp_2009, dtype: int64

In [25]:
#Drop = True -> state set as an index, dropped out of the data so it doesn't become a self-reference
state_gdp = state_gdp.set_index('state', drop=True)
state_gdp.head()

,state_code,gdp_2009,gdp_2010,gdp_2011,gdp_2012,gdp_growth_2009,gdp_growth_2010,gdp_growth_2011,gdp_growth_2012,region
state,,,,,,,,,,
Alaska,AK,44215,43472,44232,44732,7.7,-1.7,1.7,1.1,FW
Alabama,AL,149843,153839,155390,157272,-3.9,2.7,1.0,1.2,SE
Arkansas,AR,89776,92075,92684,93892,-2.0,2.6,0.7,1.3,SE
Arizona,AZ,221405,221016,224787,230641,-8.2,-0.2,1.7,2.6,SW
California,CA,1667152,1672473,1692301,1751002,-5.1,0.3,1.2,3.5,FW

In [26]:
state_gdp.loc['Alaska', ['state_code', 'region']]

state_code    AK
region        FW
Name: Alaska, dtype: str

In [27]:
#Or...
state_gdp.iloc[0,0]

'AK'

In [28]:
#Filtering data: show only data for which gdp in 2012 was higher than median gdp in the same year
state_gdp[state_gdp['gdp_2012']>state_gdp['gdp_2012'].median()].head()

,state_code,gdp_2009,gdp_2010,gdp_2011,gdp_2012,gdp_growth_2009,gdp_growth_2010,gdp_growth_2011,gdp_growth_2012,region
state,,,,,,,,,,
Arizona,AZ,221405,221016,224787,230641,-8.2,-0.2,1.7,2.6,SW
California,CA,1667152,1672473,1692301,1751002,-5.1,0.3,1.2,3.5,FW
Colorado,CO,225984,230976,234929,239884,-2.2,2.2,1.7,2.1,RM
Connecticut,CT,195237,197613,197452,197202,-3.6,1.2,-0.1,-0.1,NE
Florida,FL,648642,650291,656346,672287,-5.9,0.3,0.9,2.4,SE

In [30]:
new_df = state_gdp[state_gdp['gdp_2012']>state_gdp['gdp_2012'].median()].head()
new_df

,state_code,gdp_2009,gdp_2010,gdp_2011,gdp_2012,gdp_growth_2009,gdp_growth_2010,gdp_growth_2011,gdp_growth_2012,region
state,,,,,,,,,,
Arizona,AZ,221405,221016,224787,230641,-8.2,-0.2,1.7,2.6,SW
California,CA,1667152,1672473,1692301,1751002,-5.1,0.3,1.2,3.5,FW
Colorado,CO,225984,230976,234929,239884,-2.2,2.2,1.7,2.1,RM
Connecticut,CT,195237,197613,197452,197202,-3.6,1.2,-0.1,-0.1,NE
Florida,FL,648642,650291,656346,672287,-5.9,0.3,0.9,2.4,SE

In [31]:
#group by region and mean gdp_2012 for each region
state_gdp.groupby('region').agg({'gdp_2012': ['mean', 'std']})

             gdp_2012
                 mean            std
region
FW      413902.166667  662967.161956
GL      371729.200000  149224.466391
MW      401867.500000  360630.038276
NE      120221.000000  130466.341321
PL      125861.000000   84555.790969
RM       93468.800000   88112.812787
SE      246283.666667  179108.042047
SW      412832.000000  536592.913690