In [6]:
import numpy as np
import pandas as pd
a = np.array([0.1, 1.2, 2.3, 3.4, 4.5])
a

array([0.1, 1.2, 2.3, 3.4, 4.5])

In [7]:
s = pd.Series([0.1, 1.2, 2.3, 3.4, 4.5])
s

0    0.1
1    1.2
2    2.3
3    3.4
4    4.5
dtype: float64

In [15]:
s = pd.Series([0.1, 1.2, 2.3, 3.4, 4.5], index = ['a', 'b', 'c', 'd', 'e'])
s

a    0.1
b    1.2
c    2.3
d    3.4
e    4.5
dtype: float64

In [10]:
s['a']

np.float64(0.1)

In [13]:
s.iloc[0]

np.float64(0.1)

In [16]:
s[['a', 'c']]

a    0.1
c    2.3
dtype: float64

In [18]:
s.iloc[[0,2]]

a    0.1
c    2.3
dtype: float64

In [21]:
s[:2]

a    0.1
b    1.2
dtype: float64

In [22]:
s[s>2]

c    2.3
d    3.4
e    4.5
dtype: float64

In [23]:
s = pd.Series({'a': 0.1, 'b': 1.2, 'c': 2.3})
s*2.0

a    0.2
b    2.4
c    4.6
dtype: float64

In [24]:
s - 1.0

a   -0.9
b    0.2
c    1.3
dtype: float64

In [25]:
s2 = pd.Series({'a': 1.0, 'b':2.0, 'c':3.0})
s3 = pd.Series({'c': 0.1, 'd': 1.2, 'e': 2.3})
s + s2

a    1.1
b    3.2
c    5.3
dtype: float64

In [26]:
s*s2

a    0.1
b    2.4
c    6.9
dtype: float64

In [28]:
s + s3

a    NaN
b    NaN
c    2.4
d    NaN
e    NaN
dtype: float64

In [35]:
s1 = pd.Series([1.0, 2, 3], index=['a'] * 3)
s1

a    1.0
a    2.0
a    3.0
dtype: float64

In [36]:
s1['a']

a    1.0
a    2.0
a    3.0
dtype: float64

In [44]:
s1 = pd.Series([1.0, 2, 3])
s1.values

array([1., 2., 3.])

In [45]:
s1.index

RangeIndex(start=0, stop=3, step=1)

In [46]:
s1.index.values

array([0, 1, 2])

In [51]:
s1.index = ['cat', 'dog', 'elephant']
s1.index

Index(['cat', 'dog', 'elephant'], dtype='str')

In [49]:
s1.index.dtype

dtype('int64')

In [52]:
s = pd.Series([1.0,2,3], index = [7,2,8])
s[0]

KeyError: 0

In [53]:
s.iloc[0]

np.float64(1.0)

In [54]:
s.iloc[::2]

7    1.0
8    3.0
dtype: float64

In [57]:
#s.loc allows access using index labels or logical arrays
s.loc[[7,8]]

7    1.0
8    3.0
dtype: float64

In [58]:
s.loc[0]

KeyError: 0

In [59]:
s.iloc[1]

np.float64(2.0)

In [60]:
s.loc[1]

KeyError: 1

In [61]:
s.loc[s.index<8]

7    1.0
2    2.0
dtype: float64

In [62]:
s.iloc[s.index<8]

7    1.0
2    2.0
dtype: float64

In [67]:
s1 = pd.Series(np.arange(10.0, 20.0))
s1.describe()

count    10.00000
mean     14.50000
std       3.02765
min      10.00000
25%      12.25000
50%      14.50000
75%      16.75000
max      19.00000
dtype: float64

In [68]:
s1 = pd.Series(np.arange(1.0, 6), index = ['a','a','b','c','d'])
s1

a    1.0
a    2.0
b    3.0
c    4.0
d    5.0
dtype: float64

In [69]:
s1.drop('a')

b    3.0
c    4.0
d    5.0
dtype: float64

In [75]:
#Note: arange() follows n-1 practice like locational indexes (last number is excluded)
s1 = pd.Series(np.arange(1.0,4.0),index=['a','b','c'])
s2 = pd.Series(np.arange(1.0,4.0),index=['c','d','e'])
s1

a    1.0
b    2.0
c    3.0
dtype: float64

In [77]:
s3 = s1 + s2
s3

a    NaN
b    NaN
c    4.0
d    NaN
e    NaN
dtype: float64

In [78]:
s3.dropna()

c    4.0
dtype: float64

In [79]:
s3=s1+s2
s3

a    NaN
b    NaN
c    4.0
d    NaN
e    NaN
dtype: float64

In [80]:
s3.fillna(-1.0)

a   -1.0
b   -1.0
c    4.0
d   -1.0
e   -1.0
dtype: float64

In [83]:
s3 = pd.concat([s1, s2])
s3

a    1.0
b    2.0
c    3.0
c    1.0
d    2.0
e    3.0
dtype: float64

In [85]:
s1 = pd.Series(np.arange(1.0,4.0), index=['a', 'b', 'c'])
s1

a    1.0
b    2.0
c    3.0
dtype: float64

In [88]:
s2 = pd.Series(-1.0*np.arange(1.0,4.0),index=['c','d','e'])
s1.update(s2)
s1

a    1.0
b    2.0
c   -1.0
dtype: float64

In [89]:
s1 = pd.Series(np.arange(1.0,4.0), index=['a', 'b', 'c'])
s1

a    1.0
b    2.0
c    3.0
dtype: float64

In [91]:
a = np.array([[1.0,2],[3,4]])
df = pd.DataFrame(a)
df

     0    1
0  1.0  2.0
1  3.0  4.0

In [93]:
df = pd.DataFrame(a, columns=['a','b'])
df

     a    b
0  1.0  2.0
1  3.0  4.0

In [94]:
df.columns = ['cats', 'dogs']
df

   cats  dogs
0   1.0   2.0
1   3.0   4.0

In [95]:
df.index = ['Alice', 'Bob']
df

       cats  dogs
Alice   1.0   2.0
Bob     3.0   4.0

In [98]:
import datetime as dt
t = np.dtype([('datetime', 'O8'), ('value', 'f4')])
x = np.zeros(1,dtype=t)
x[0][0] = dt.datetime(2013,1,1)
x[0][1] = -99.99
x

array([(datetime.datetime(2013, 1, 1, 0, 0), -99.99)],
      dtype=[('datetime', 'O'), ('value', '<f4')])

In [99]:
s1 = pd.Series(np.arange(0.0,5))
s2 = pd.Series(np.arange(1.0,3))
pd.DataFrame({'one': s1, 'two': s2})

   one  two
0  0.0  1.0
1  1.0  2.0
2  2.0  NaN
3  3.0  NaN
4  4.0  NaN

In [100]:
s3 = pd.Series(np.arange(0.0, 3))
pd.DataFrame({'one': s1, 'two': s2, 'three': s3})

   one  two  three
0  0.0  1.0    0.0
1  1.0  2.0    1.0
2  2.0  NaN    2.0
3  3.0  NaN    NaN
4  4.0  NaN    NaN

In [101]:
state_gdp = pd.read_excel('US_state_GDP.xls', 'Sheet1')
state_gdp.head()

,state_code,state,gdp_2009,gdp_2010,gdp_2011,gdp_2012,gdp_growth_2009,gdp_growth_2010,gdp_growth_2011,gdp_growth_2012,region
0,AK,Alaska,44215,43472,44232,44732,7.7,-1.7,1.7,1.1,FW
1,AL,Alabama,149843,153839,155390,157272,-3.9,2.7,1.0,1.2,SE
2,AR,Arkansas,89776,92075,92684,93892,-2.0,2.6,0.7,1.3,SE
3,AZ,Arizona,221405,221016,224787,230641,-8.2,-0.2,1.7,2.6,SW
4,CA,California,1667152,1672473,1692301,1751002,-5.1,0.3,1.2,3.5,FW

In [102]:
state_gdp ['state_code'].head() #Series

0    AK
1    AL
2    AR
3    AZ
4    CA
Name: state_code, dtype: str

In [103]:
state_gdp[['state_code']].head() #DataFrame

  state_code
0         AK
1         AL
2         AR
3         AZ
4         CA

In [104]:
state_gdp[['state_code','state']].head()

  state_code       state
0         AK      Alaska
1         AL     Alabama
2         AR    Arkansas
3         AZ     Arizona
4         CA  California

In [106]:
cols = state_gdp.columns #Creates a list of Series titles
state_gdp[cols[1:3]].head()

        state  gdp_2009
0      Alaska     44215
1     Alabama    149843
2    Arkansas     89776
3     Arizona    221405
4  California   1667152