# Homework #3

## Chapter 3

### Problem #1

In [1]:
#u = [1 1 2 3 5 8]
import numpy as np
u = np.array([1, 1, 2, 3, 5, 8])
u

array([1, 1, 2, 3, 5, 8])

In [2]:
# v = column vector transpose of u
v = np.array([[1],[1],[2],[3],[5],[8]])
v

array([[1],
       [1],
       [2],
       [3],
       [5],
       [8]])

In [3]:
#x = 2x2 identity matrix
x = np.array([[1, 0], [0,1]])
x

array([[1, 0],
       [0, 1]])

In [4]:
#y = Row 1: 1, 2; Row 2: 3, 4
y = np.array([[1, 2], [3, 4]])
y

array([[1, 2],
       [3, 4]])

In [5]:
#z = Row 1: 1,2,1,2; Row 2: 3,4,3,4; Row 3: 1,2,1,2
z= np.array([[1,2,1,2], [3,4,3,4], [1,2,1,2]])
z

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2]])

In [6]:
#w = Row 1: x,x; Row 2: y,y
w0 = np.hstack((x,x))
w1 = np.hstack((y,y))
w = np.vstack((w0,w1))
w

array([[1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])

If I compressed this into one line, I would run a vstack on the sequential hstacks.

In [7]:
w = np.vstack((np.hstack((x, x)), np.hstack((y, y))))
w

array([[1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])

## Chapter 5

### Problem 3

In [8]:
y = np.array([0,0.5,1.5,2.5,1.0,1.0001,-0.5,-1,-1.5,-2.5])
y

array([ 0.    ,  0.5   ,  1.5   ,  2.5   ,  1.    ,  1.0001, -0.5   ,
       -1.    , -1.5   , -2.5   ])

In [9]:
y.round(2)

array([ 0. ,  0.5,  1.5,  2.5,  1. ,  1. , -0.5, -1. , -1.5, -2.5])

In [10]:
y.round()

array([ 0.,  0.,  2.,  2.,  1.,  1., -0., -1., -2., -2.])

In [11]:
#Or, alternatively...
np.around(y, 2)

array([ 0. ,  0.5,  1.5,  2.5,  1. ,  1. , -0.5, -1. , -1.5, -2.5])

In [12]:
np.around(y)

array([ 0.,  0.,  2.,  2.,  1.,  1., -0., -1., -2., -2.])

In [13]:
np.floor(y)

array([ 0.,  0.,  1.,  2.,  1.,  1., -1., -1., -2., -3.])

In [14]:
np.ceil(y)

array([ 0.,  1.,  2.,  3.,  1.,  2., -0., -1., -1., -2.])

In words, round() and around() will round the values in the array to the nearest integer, unless we specify decimal place precision, in which case it rounds figures to that many decimal places. This means that values <= 0.5 are rounded down to zero, and everything 0.5 < x <=1 rounds up to 1. floor() will round down to the nearest lower integer, so x<1 rounds down to 0. ceil() rounds up to the nearest larger integer, so x<=1 rounds up to 1.

## Chapter 16

### Problem 1

Create Series:
(a) s1 with the values “apple”, “banana”, “cherry” with the name “fruit”.
(b) s2 with the values 3.14, 2.71, 1.61 with the name “transcendentals”.

In [15]:
import pandas as pd
s1 = pd.Series(['apple', 'banana', 'cherry'], name = 'fruit')
s1

0     apple
1    banana
2    cherry
Name: fruit, dtype: str

In [16]:
s2 = pd.Series([3.14, 2.71, 1.61], name = 'transcendentals')
s2

0    3.14
1    2.71
2    1.61
Name: transcendentals, dtype: float64

### Problem 2

In [17]:
d1 = pd.DataFrame(np.array([[1,2,3],[2,3,4],[3,4,5],[4,5,6]]), index = ['a','b','c','d'], columns = ['a','b','c'])
d1

   a  b  c
a  1  2  3
b  2  3  4
c  3  4  5
d  4  5  6

In [18]:
d2 = pd.DataFrame(np.array([[1,2,3],[1,2,3],[1,2,3]]), columns = ['Albania', 'Belgium', 'Canada'])
d2

   Albania  Belgium  Canada
0        1        2       3
1        1        2       3
2        1        2       3

In [19]:
d3 = pd.DataFrame(np.array([[0,1,2],[3,4,5],[6,7,8]]))
d3

   0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

### Problem 3
Extract b from d1 using [] notation and Albania from d2 using dot notation (.).

This problem doesn't explicitly tell us whether we are extracting row b or column b from d1, so I'll do both just to be safe.

In [20]:
#Column b
d1['b']

a    2
b    3
c    4
d    5
Name: b, dtype: int64

In [21]:
#Row b
d1.iloc[1]

a    2
b    3
c    4
Name: b, dtype: int64

In [22]:
#Column Albania
d2.Albania

0    1
1    1
2    1
Name: Albania, dtype: int64

### Problem 4
Select the European countries from d2.

In [23]:
d2[['Albania','Belgium']]

   Albania  Belgium
0        1        2
1        1        2
2        1        2

### Problem 5

In [24]:
#Create series s3
s3 = pd.Series(np.array([4,4,4]), name = 'Denmark')
s3

0    4
1    4
2    4
Name: Denmark, dtype: int64

In [28]:
#Add s3 to d2
d2.insert(3, 'Denmark', s3)
d2

   Albania  Belgium  Canada  Denmark
0        1        2       3        4
1        1        2       3        4
2        1        2       3        4

In [29]:
#Could also have done
# d2['Denmark'] = s3
# but would have automatically put Denmark at the end.
#Insert gives us control over which index position Denmark series will occupy.

### Problem 6

In [38]:
d2c = d2.copy()
del d2c['Canada']
d2c

   Albania  Belgium  Denmark
0        1        2        4
1        1        2        4
2        1        2        4

In [39]:
s4 = d2c.pop('Denmark')
d2c

   Albania  Belgium
0        1        2
1        1        2
2        1        2

In [40]:
s4

0    4
1    4
2    4
Name: Denmark, dtype: int64

### Problem 7

Merge s1 and s2 into a new DataFrame d4.

In [41]:
#Choose axis = 1 to align each series as a column, 
#rather than stacking s2 beneath s1 in a single column if using axis = 0
d4 = pd.concat((s1, s2), axis = 1)
d4

    fruit  transcendentals
0   apple             3.14
1  banana             2.71
2  cherry             1.61